project:
  type: book
  output-dir: docs

book:
  title: "DownClim - Downscale Climate Projections"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - test_nc.qmd
  appendices:
    - literature.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
