# Area
area: ["New-Caledonia", "Vanuatu"]

# Time
time_frequency: "mon"
hist_years: ["1980-2005"]
eval_years: ["2006-2019"]
proj_years: ["2071-2100"]

# Variables
variables: ["tas", "tasmin", "tasmax", "pr"]

# Baseline
baseline: "chelsa2"
base_years: "1980-2018" # 2019 is available for all except pr !!!

# Projection
projections: "config/projections_ex.tsv"
domains: "config/domains.tsv"
esgf_credential: "config/credentials_esgf.yml"

# Downscaling
aggregation: "monthly-means"
ds_method: "bc"

# Evaluation
base_eval: "chelsa2"
